"""add_relevance_threshold_boost_factor

Revision ID: 10400fbbe32d
Revises: c43b8a7e57bc
Create Date: 2025-10-10 23:51:29.810582

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '10400fbbe32d'
down_revision = 'c43b8a7e57bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_profiles', sa.Column('relevance_threshold', sa.Integer(), nullable=False))
    op.add_column('interest_profiles', sa.Column('boost_factor', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interest_profiles', 'boost_factor')
    op.drop_column('interest_profiles', 'relevance_threshold')
    # ### end Alembic commands ###
