"""Add RSS validation fields to ContentSource

Revision ID: c43b8a7e57bc
Revises: 1e9bf615540f
Create Date: 2025-09-24 17:52:33.245961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c43b8a7e57bc'
down_revision = '1e9bf615540f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_sources', sa.Column('validation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('content_sources', sa.Column('last_validated_at', sa.DateTime(), nullable=True))
    op.add_column('content_sources', sa.Column('validation_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('content_sources', sa.Column('last_fetch_at', sa.DateTime(), nullable=True))
    op.add_column('content_sources', sa.Column('last_fetch_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_sources', 'last_fetch_count')
    op.drop_column('content_sources', 'last_fetch_at')
    op.drop_column('content_sources', 'validation_error')
    op.drop_column('content_sources', 'last_validated_at')
    op.drop_column('content_sources', 'validation_status')
    # ### end Alembic commands ###
